#If you want to write log files in addition to the console output you need to set a logging.file or logging.path property
spring:
  profiles:
    active: @profiles.active@,swagger,actuator,ssl,tomcat,shell
logging:
  file: logs/todo.log
  level:
    root: info