#Web UI和Rest API分开部署，使用不同的域名。
#WebUI在请求RestAPI时会报错：
#“No 'Access-Control-Origin' header is present on the requested resource."
#因为AJAX的安全限制，不支持跨域 :cors :Cross-Origin Resource Sharing
endpoints:
  cors:
    allowed-origins: http://baidu.com
    allowed-methods: GET,POST,PUT,DELETE