spring:
     datasource:
       url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
       username: root
       password:
     jpa:
       show-sql: true
       hibernate:
         ddl-auto:  create-drop
         naming:
           strategy: org.hibernate.cfg.ImprovedNamingStrategy
       properties:
          hibernate:
              format_sql: true
              use_sql_comments: true
     thymeleaf:
       cache: false